-- ─────────────────────────────────────────────────────────────────────────────
-- BenefitsPath Supabase Schema
-- Run this entire file in: Supabase Dashboard → SQL Editor → New Query → Run
-- ─────────────────────────────────────────────────────────────────────────────

-- ── LEADS TABLE ───────────────────────────────────────────────────────────────
create table if not exists leads (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now(),
  type            text,           -- 'eligibility' | 'appeal_letter' | 'attorney_request'
  email           text,
  first_name      text,
  last_name       text,
  phone           text,
  state           text,
  end_reason      text,
  employment_length text,
  application_status text,
  eligibility_score integer,
  eligibility_likelihood text,
  lawyer_name     text,
  lawyer_phone    text,
  lawyer_email    text,
  lawyer_situation text,
  appeal_first_name text,
  appeal_last_name text
);

-- ── ATTORNEYS TABLE ───────────────────────────────────────────────────────────
create table if not exists attorneys (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  name        text not null,
  firm        text,
  phone       text,
  email       text,
  website     text,
  bio         text,
  tags        text[],            -- e.g. ARRAY['UI Appeals', 'Wrongful Termination']
  states      text[],            -- e.g. ARRAY['CA', 'TX'] or ARRAY['ALL']
  featured    boolean default false,
  paid_tier   text default 'basic',  -- 'basic' | 'premium' | 'featured'
  active      boolean default true
);

-- ── ROW LEVEL SECURITY ────────────────────────────────────────────────────────
-- Leads: only the service role can read/write (your API uses service role key)
alter table leads enable row level security;
create policy "Service role only" on leads
  using (auth.role() = 'service_role');

-- Attorneys: anyone can read active listings, only service role can write
alter table attorneys enable row level security;
create policy "Public read active attorneys" on attorneys
  for select using (active = true);
create policy "Service role write attorneys" on attorneys
  for all using (auth.role() = 'service_role');

-- ── SAMPLE ATTORNEY DATA (delete or update before going live) ─────────────────
insert into attorneys (name, firm, phone, email, tags, states, featured, paid_tier) values
  ('Sarah Mitchell', 'Mitchell Employment Law', '1-800-555-0101', 'sarah@mitchelllaw.com',
   ARRAY['Wrongful Termination', 'UI Appeals', 'Discrimination'],
   ARRAY['ALL'], true, 'featured'),
  ('James Reyes', 'Reyes & Associates', '1-800-555-0102', 'james@reyeslaw.com',
   ARRAY['UI Denials', 'Contractor Disputes'],
   ARRAY['CA', 'TX', 'FL', 'NY'], false, 'premium');
